on:
  push:
    branches:
      - main

name: Build Prod

env:
  APP_DIR: /root/teledrive
  DEV_USER: root
  DEV_HOST_SG_1: 159.223.92.212
  DEV_HOST_SG_2: 157.245.151.235
  DEV_HOST_SG_3: 159.223.94.162
  DEV_HOST_GE_DB: 104.248.23.115
  DEV_HOST_GE_1: 159.89.108.133
  DEV_HOST_GE_2: 165.227.157.185
  DEV_HOST_US_DB: 143.198.121.121
  DEV_HOST_US_1: 143.198.114.6

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Add npmrc
      run: echo -e "//npm.pkg.github.com/:_authToken=${NPM_AUTH_TOKEN}\n@mgilangjanuar:registry=https://npm.pkg.github.com/" > ~/.npmrc && cat ~/.npmrc
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - run: yarn install
    - run: GENERATE_SOURCEMAP=false yarn workspaces run build
    - name: Compress node_modules root
      if: ${{ github.event_name == 'push' }}
      run: tar -czf build-root.tar.gz node_modules
    - name: Compress node_modules & dist server
      if: ${{ github.event_name == 'push' }}
      run: tar -czf build-server.tar.gz server/node_modules server/dist
    - name: Compress node_modules & build web
      if: ${{ github.event_name == 'push' }}
      run: tar -czf build-web.tar.gz web/node_modules web/build

    # Upload to SG_1
    - name: Upload build-root.tar.gz to sg_1
      uses: appleboy/scp-action@master
      with:
        source: build-root.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_SG_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
        debug: true
    - name: Upload build-server.tar.gz to sg_1
      uses: appleboy/scp-action@master
      with:
        source: build-server.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_SG_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Upload build-web.tar.gz to sg_1
      uses: appleboy/scp-action@master
      with:
        source: build-web.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_SG_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}

    # Upload to SG_2
    - name: Upload build-root.tar.gz to sg_2
      uses: appleboy/scp-action@master
      with:
        source: build-root.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_SG_2 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
        debug: true
    - name: Upload build-server.tar.gz to sg_2
      uses: appleboy/scp-action@master
      with:
        source: build-server.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_SG_2 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Upload build-web.tar.gz to sg_2
      uses: appleboy/scp-action@master
      with:
        source: build-web.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_SG_2 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}

    # Upload to SG_3
    - name: Upload build-root.tar.gz to sg_3
      uses: appleboy/scp-action@master
      with:
        source: build-root.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_SG_3 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
        debug: true
    - name: Upload build-server.tar.gz to sg_3
      uses: appleboy/scp-action@master
      with:
        source: build-server.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_SG_3 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Upload build-web.tar.gz to sg_3
      uses: appleboy/scp-action@master
      with:
        source: build-web.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_SG_3 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}


    # Upload to GE_1
    - name: Upload build-root.tar.gz to ge_1
      uses: appleboy/scp-action@master
      with:
        source: build-root.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_GE_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
        debug: true
    - name: Upload build-server.tar.gz to ge_1
      uses: appleboy/scp-action@master
      with:
        source: build-server.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_GE_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Upload build-web.tar.gz to ge_1
      uses: appleboy/scp-action@master
      with:
        source: build-web.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_GE_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}

    # Upload to GE_2
    - name: Upload build-root.tar.gz to ge_2
      uses: appleboy/scp-action@master
      with:
        source: build-root.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_GE_2 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
        debug: true
    - name: Upload build-server.tar.gz to ge_2
      uses: appleboy/scp-action@master
      with:
        source: build-server.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_GE_2 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Upload build-web.tar.gz to ge_2
      uses: appleboy/scp-action@master
      with:
        source: build-web.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_GE_2 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}

    # Upload to GE_DB
    - name: Upload build-root.tar.gz to ge_db
      uses: appleboy/scp-action@master
      with:
        source: build-root.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_GE_DB }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
        debug: true
    - name: Upload build-server.tar.gz to ge_db
      uses: appleboy/scp-action@master
      with:
        source: build-server.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_GE_DB }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Upload build-web.tar.gz to ge_db
      uses: appleboy/scp-action@master
      with:
        source: build-web.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_GE_DB }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}


    # Upload to US_DB
    - name: Upload build-root.tar.gz to us_db
      uses: appleboy/scp-action@master
      with:
        source: build-root.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_US_DB }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
        debug: true
    - name: Upload build-server.tar.gz to us_db
      uses: appleboy/scp-action@master
      with:
        source: build-server.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_US_DB }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Upload build-web.tar.gz to us_db
      uses: appleboy/scp-action@master
      with:
        source: build-web.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_US_DB }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}

    # Upload to US_1
    - name: Upload build-root.tar.gz to us_1
      uses: appleboy/scp-action@master
      with:
        source: build-root.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_US_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
        debug: true
    - name: Upload build-server.tar.gz to us_1
      uses: appleboy/scp-action@master
      with:
        source: build-server.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_US_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Upload build-web.tar.gz to us_1
      uses: appleboy/scp-action@master
      with:
        source: build-web.tar.gz
        target: ${{ env.APP_DIR }}
        host: ${{ env.DEV_HOST_US_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}


    # Deployment SG_1
    - name: Extract build-root.tar.gz to sg_1
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }} && rm -rf node_modules && tar -xzf build-root.tar.gz && rm -rf build-root.tar.gz
        host: ${{ env.DEV_HOST_SG_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-web.tar.gz to sg_1
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/web && rm -rf node_modules && rm -rf build && cd .. && tar -xzf build-web.tar.gz && rm -rf build-web.tar.gz
        host: ${{ env.DEV_HOST_SG_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-server.tar.gz to sg_1
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/server && rm -rf node_modules && rm -rf dist && cd .. && tar -xzf build-server.tar.gz && rm -rf build-server.tar.gz && git pull origin main --rebase && cd ${{ env.APP_DIR }} && /usr/local/bin/pm2 restart td
        host: ${{ env.DEV_HOST_SG_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}

    # Deployment SG_2
    - name: Extract build-root.tar.gz to sg_2
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }} && rm -rf node_modules && tar -xzf build-root.tar.gz && rm -rf build-root.tar.gz
        host: ${{ env.DEV_HOST_SG_2 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-web.tar.gz to sg_2
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/web && rm -rf node_modules && rm -rf build && cd .. && tar -xzf build-web.tar.gz && rm -rf build-web.tar.gz
        host: ${{ env.DEV_HOST_SG_2 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-server.tar.gz to sg_2
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/server && rm -rf node_modules && rm -rf dist && cd .. && tar -xzf build-server.tar.gz && rm -rf build-server.tar.gz && git pull origin main --rebase && cd ${{ env.APP_DIR }} && /usr/local/bin/pm2 restart td
        host: ${{ env.DEV_HOST_SG_2 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}

    # Deployment SG_3
    - name: Extract build-root.tar.gz to sg_3
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }} && rm -rf node_modules && tar -xzf build-root.tar.gz && rm -rf build-root.tar.gz
        host: ${{ env.DEV_HOST_SG_3 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-web.tar.gz to sg_3
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/web && rm -rf node_modules && rm -rf build && cd .. && tar -xzf build-web.tar.gz && rm -rf build-web.tar.gz
        host: ${{ env.DEV_HOST_SG_3 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-server.tar.gz to sg_3
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/server && rm -rf node_modules && rm -rf dist && cd .. && tar -xzf build-server.tar.gz && rm -rf build-server.tar.gz && git pull origin main --rebase && cd ${{ env.APP_DIR }} && /usr/local/bin/pm2 restart td
        host: ${{ env.DEV_HOST_SG_3 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}


    # Deployment GE_1
    - name: Extract build-root.tar.gz to ge_1
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }} && rm -rf node_modules && tar -xzf build-root.tar.gz && rm -rf build-root.tar.gz
        host: ${{ env.DEV_HOST_GE_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-web.tar.gz to ge_1
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/web && rm -rf node_modules && rm -rf build && cd .. && tar -xzf build-web.tar.gz && rm -rf build-web.tar.gz
        host: ${{ env.DEV_HOST_GE_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-server.tar.gz to ge_1
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/server && rm -rf node_modules && rm -rf dist && cd .. && tar -xzf build-server.tar.gz && rm -rf build-server.tar.gz && git pull origin main --rebase && cd ${{ env.APP_DIR }} && /usr/local/bin/pm2 restart td
        host: ${{ env.DEV_HOST_GE_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}

    # Deployment GE_2
    - name: Extract build-root.tar.gz to ge_2
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }} && rm -rf node_modules && tar -xzf build-root.tar.gz && rm -rf build-root.tar.gz
        host: ${{ env.DEV_HOST_GE_2 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-web.tar.gz to ge_2
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/web && rm -rf node_modules && rm -rf build && cd .. && tar -xzf build-web.tar.gz && rm -rf build-web.tar.gz
        host: ${{ env.DEV_HOST_GE_2 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-server.tar.gz to ge_2
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/server && rm -rf node_modules && rm -rf dist && cd .. && tar -xzf build-server.tar.gz && rm -rf build-server.tar.gz && git pull origin main --rebase && cd ${{ env.APP_DIR }} && /usr/local/bin/pm2 restart td
        host: ${{ env.DEV_HOST_GE_2 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}

    # Deployment GE_DB
    - name: Extract build-root.tar.gz to ge_db
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }} && rm -rf node_modules && tar -xzf build-root.tar.gz && rm -rf build-root.tar.gz
        host: ${{ env.DEV_HOST_GE_DB }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-web.tar.gz to ge_db
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/web && rm -rf node_modules && rm -rf build && cd .. && tar -xzf build-web.tar.gz && rm -rf build-web.tar.gz
        host: ${{ env.DEV_HOST_GE_DB }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-server.tar.gz to ge_db
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/server && rm -rf node_modules && rm -rf dist && cd .. && tar -xzf build-server.tar.gz && rm -rf build-server.tar.gz && git pull origin main --rebase && cd ${{ env.APP_DIR }} && /usr/local/bin/pm2 restart td
        host: ${{ env.DEV_HOST_GE_DB }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}


    # Deployment US_DB
    - name: Extract build-root.tar.gz to us_db
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }} && rm -rf node_modules && tar -xzf build-root.tar.gz && rm -rf build-root.tar.gz
        host: ${{ env.DEV_HOST_US_DB }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-web.tar.gz to us_db
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/web && rm -rf node_modules && rm -rf build && cd .. && tar -xzf build-web.tar.gz && rm -rf build-web.tar.gz
        host: ${{ env.DEV_HOST_US_DB }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-server.tar.gz to us_db
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/server && rm -rf node_modules && rm -rf dist && cd .. && tar -xzf build-server.tar.gz && rm -rf build-server.tar.gz && git pull origin main --rebase && cd ${{ env.APP_DIR }} && /usr/local/bin/pm2 restart td
        host: ${{ env.DEV_HOST_US_DB }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}

    # Deployment US_1
    - name: Extract build-root.tar.gz to us_1
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }} && rm -rf node_modules && tar -xzf build-root.tar.gz && rm -rf build-root.tar.gz
        host: ${{ env.DEV_HOST_US_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-web.tar.gz to us_1
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/web && rm -rf node_modules && rm -rf build && cd .. && tar -xzf build-web.tar.gz && rm -rf build-web.tar.gz
        host: ${{ env.DEV_HOST_US_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}
    - name: Extract build-server.tar.gz to us_1
      if: ${{ github.event_name == 'push' }}
      uses: appleboy/ssh-action@master
      with:
        script: cd ${{ env.APP_DIR }}/server && rm -rf node_modules && rm -rf dist && cd .. && tar -xzf build-server.tar.gz && rm -rf build-server.tar.gz && git pull origin main --rebase && cd ${{ env.APP_DIR }} && /usr/local/bin/pm2 restart td
        host: ${{ env.DEV_HOST_US_1 }}
        username: ${{ env.DEV_USER }}
        key: ${{ secrets.SSH_SECRET }}

    - name: Success Notification
      uses: appleboy/telegram-action@master
      with:
        to: -700697945
        token: ${{ secrets.TG_BOT_TOKEN }}
        message: |
          ðŸŽ‰ *Deployed to Production*

          Please take a look -> https://teledriveapp.com https://ge.teledriveapp.com https://us.teledriveapp.com
        format: markdown
    - name: Failed Notification
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      with:
        to: -700697945
        token: ${{ secrets.TG_BOT_TOKEN }}
        message: |
          ðŸ”¥ *Deploy to Production Failed!*

          Please take a look -> https://github.com/mgilangjanuar/teledrive/actions
        format: markdown